/*
================================================================================
Description: An analysis of apparel customer shopping behavior, focusing on revenue trends,
product performance, discount impact, shipping preferences, and customer segmentation.
The analysis leverages aggregations, conditional logic, common table expressions (CTEs),
and window functions to support business insights.
================================================================================
*/

-- ============================================================================
-- 1. REVENUE ANALYSIS
-- ============================================================================

-- Total revenue generated by male vs. female customers
SELECT 
    gender, SUM(purchase_amount) AS revenue
FROM
    customer_shopping
GROUP BY gender;

-- Revenue by Age Group
select age_group,
sum(purchase_amount) as revenue
from customer_shopping
group by age_group
order by revenue desc;


-- ============================================================================
-- 2. DISCOUNT IMPACT ANALYSIS
-- ============================================================================

--  Discount users who still spent more than the average
select customer_id,
purchase_amount
from customer_shopping
where discount_applied = "Yes" and 
purchase_amount >= (
select avg(purchase_amount)
from customer_shopping
);


-- ============================================================================
-- 3. PRODUCT PERFORMANCE
-- ============================================================================

-- Top 5 products with highest average rating
select item_purchased,
round(avg(review_rating),2)  as avg_rating
from customer_shopping
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Top 3 Most Purchased products per Category
with item_totals as 
( 
select category,
 item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer_shopping
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_totals
where item_rank <= 3;

--  Top 5 products with highest discount usage percentage
select item_purchased,
round(100 * sum(case when discount_applied = "Yes" then 1
else 0 end) /
count(*), 2) as product_percentage
from customer_shopping
group by item_purchased
order by product_percentage desc
limit 5;


-- ============================================================================
-- 4. SHIPPING ANALYSIS
-- ============================================================================

-- Comparison of purchase amount across all shipping types
select shipping_type,
round(avg(purchase_amount), 2)
from customer_shopping
group by shipping_type
order by avg(purchase_amount) desc;

-- Comparison of Purchase Amount between Express and Standard Shipping Types
select shipping_type,
round(avg(purchase_amount), 2) as avg_purchase
from customer_shopping
where shipping_type in ("Standard", "Express")
group by shipping_type
order by avg(purchase_amount) desc;


-- ============================================================================
-- 5. SUBSCRIPTION ANALYSIS
-- ============================================================================

-- Spending behaviour comparison between subscribers and non subscribers
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount), 2) as avg_purchase,
sum(purchase_amount) as total_revenue
from customer_shopping
group by subscription_status
order by total_revenue, avg_purchase;

-- Are repeat buyers likely to be subscribers?
select subscription_status,
count(customer_id) as repeat_buyers
from customer_shopping
where previous_purchases > 5
group by subscription_status;


-- ============================================================================
-- 6. CUSTOMER SEGMENTATION
-- ============================================================================

-- Customer Segmentation based on New, Returning, and Loyal
with customer_type as 
(
 select customer_id, previous_purchases,
 case
	when previous_purchases = 1 then "New"
	when previous_purchases between 2 and 10 then "Returning"
	else "Loyal"
	end as customer_segment
 from customer_shopping
 )
 select customer_segment, count(*) as "Number of Customers"
 from customer_type
 group by customer_segment;
 